### ISSUE TITLE
失效了吗

### ISSUE THREAD

**Issue by yueguiji** [LiZheGuang/gpt_academic_chrome_extension#1]
失效了吗

**Comment by LiZheGuang** [comment]
> 失效了吗

https://github.com/LiZheGuang/gpt_academic_chrome_extension/commit/8286a31296d554355d84fb25c9312a3ffdc2e1af
已修复，应该是作者更新了Dom元素结构导致;
另外插件需要在URL上追加  ?__theme=dark 参数才可以生效
